### PR TITLE
Feature/challenges view with boxes

### PR DESCRIPTION
**Pull request by bmlancien**
Hi @henhuy, I need your help for implementing views and layouts correctly:
- The content on the first step should not be visible on the other steps
- The left panel shouldn't be there on first step (see image below)

I can work on design issues after that if needed. For example, the "Imprint" and "Privacy" links should always be always stay at the same place, with or without panel.

I also need to add content to the popups before merging that branch.

Challenges_start (1)

### CODE REVIEW

**Comment by henhuy** [comment]
Little bug:
When I run it locally, image looks like this:
grafik

**Comment by henhuy** [comment]
> The content on the first step should not be visible on the other steps

I'm already trying to hide it. This is done in the app by adding `hidden` attribute to the element. Unfortunately, in case of `challenges` the `hidden` attribute is overwritten by following CSS entry:
grafik

Once you changed this - challenges div should be invisible on other menus...

**Comment by henhuy** [comment]
Same goes for the panel. I cannot simply hide it, as `.panel` CSS entry overwrites my `hidden` attr:
grafik

Can you change this? Or do I have to set `display: none !important` myself ?
(I really don't like the CSS implementation with battling `!important` statements)

**Comment by bmlancien** [comment]
Alright, I'll try to change this. I'm actually using Bootstrap utility classes, and these classes often come with an `!important`. In this case I will not use Bootstrap.

**Comment by bmlancien** [comment]
@henhuy I mentioned above, I removed the utility classes. It should work now.

@nesnoj I was not able to make the footer look different for different views (with and without panel) since it's quite complicated. I had to change a few things. I made it 100% width for all views and I actually don't think it's a bad idea since it looks consistent for every view. I tried to keep the footer's height as minimal as possible. What do you think? If you really want the footer to look like before when the panel is visible, I would need more time to make it work.

**Comment by henhuy** [comment]
Panel is now hidden on challenges menu.

**Comment by nesnoj** [comment]
> @nesnoj I was not able to make the footer look different for different views (with and without panel) since it's quite complicated. I had to change a few things. I made it 100% width for all views and I actually don't think it's a bad idea since it looks consistent for every view. I tried to keep the footer's height as minimal as possible. What do you think? If you really want the footer to look like before when the panel is visible, I would need more time to make it work.

Yes, the footer it's consistent and not too present, LGTM. But I propose to move the text of the footer to the right as it is somewhat conspicuous in the map view (and the main menu's text have the same orientation). ok?

**Comment by bmlancien** [comment]
> Yes, the footer it's consistent and not too present, LGTM. But I propose to move the text of the footer to the right as it is somewhat conspicuous in the map view (and the main menu's text have the same orientation). ok?

Alright, I can do that.

**Comment by bmlancien** [comment]
@nesnoj I added the placeholder content to the modals. Can @henhuy review the PR or do you want to wait to add the final content?

**Comment by henhuy** [comment]
Indeed there went something missing - fixed it. Everything should work now as expected.

**Comment by bmlancien** [comment]
> Indeed there went something missing - fixed it. Everything should work now as expected.

Alright, thanks! 

Can you merge?

**Review by nesnoj — APPROVED** [review]
Works as expected, thx!

**Pull request merged**
