### PR TITLE
Increase gunicorn timeout and workers

### PR DESCRIPTION
**Pull request by henhuy**

### CODE REVIEW

**Comment by nesnoj** [comment]
Did not solve hanging of app. Solution brought by fix in mapengine 111f4225fecdee32c52acc26b23f3a66b5e86ba4

**Comment by henhuy** [comment]
Increasing worker amount still could be a good solution - but if it works properly now, maybe we should keep it as is?!

**Comment by nesnoj** [comment]
> Increasing worker amount still could be a good solution - but if it works properly now, maybe we should keep it as is?!

Yes, you're right.

The [docs](https://docs.gunicorn.org/en/latest/design.html#how-many-workers) say
_"Gunicorn relies on the operating system to provide all of the load balancing when handling requests. Generally we recommend (2 x $num_cores) + 1 as the number of workers to start off with."_
which would result in 49 which is way too large according to other info I found.
[This thread](https://stackoverflow.com/questions/38425620/gunicorn-workers-and-threads) explains best, however there's no single truth and the optimal config depends on the number of requests, their duration and synchronicity, the docs recommend _"tune using TTIN and TTOU signals while the application is under load"_. I'd like to avoid this finetuning.
So maybe `--workers=4` is a good starting point.

And it might make sense to increase threads too.

Moreover, the [docs](https://docs.gunicorn.org/en/latest/design.html#choosing-a-worker-type) recommend async workers for certain use cases, e.g. _"Applications making long blocking calls (Ie, external web services)"_ to avoid processes being blocked. Except for WMS layers we won't have ext. resources and they are not supposed to be "long blocking calls".  ESys optimization processes run in a separate container and checked by the app frequently, so they do not block the web processes, is this correct?
What do you think about synchronicity?

**Comment by henhuy** [comment]
> So maybe `--workers=4` is a good starting point.

Yep - maybe we start with this

> Moreover, the [docs](https://docs.gunicorn.org/en/latest/design.html#choosing-a-worker-type) recommend async workers for certain use cases, e.g. _"Applications making long blocking calls (Ie, external web services)"_ to avoid processes being blocked. Except for WMS layers we won't have ext. resources and they are not supposed to be "long blocking calls". ESys optimization processes run in a separate container and checked by the app frequently, so they do not block the web processes, is this correct?
> What do you think about synchronicity?

Yes, I think you are right - except for ES simulation, we don't need async stuff and ES is already using celery, so we are fine there IMHO.

**Review by nesnoj — APPROVED** [review]
ok, thx!

**Pull request merged**
