### PR TITLE
Fix choropleth legend and RE share choropleth

### LINKED ISSUE #141: 0 - 0 in choropleth legend value
Some choropleths have legend values "0 - 0" :thinking: 
e.g. installed power, number WTs, ...

image

### LINKED ISSUE #142: Choropleth for RE share not working
for SQ, result one is working though..
```
Uncaught TypeError: Cannot read properties of null (reading 'fill-color')
    at loadLegend (legend.js:58:40)
    at callSubscriberWithDelayedExceptions (pubsub.js:67:13)
    at deliverMessage (pubsub.js:88:17)
    at deliverNamespaced (pubsub.js:99:13)
```

### PR DESCRIPTION
**Pull request by henhuy**
Fixes #142 
Fixes #141 

Needs poetry update due to fix in mapengine

### CODE REVIEW

**Review by nesnoj — COMMENTED** [review]
Thx for the fix!
The choropleth for RE share is working now.

As you set the range to 10, 100, ... the color range is not completely used leading to a map with very similar colors..which in my opinion is a drawback but I could live with that.. but it has effects like this:
image
because in one mun (Bliesdorf) the factor is 270 (which is correct) leading to 27000% but this sets the legend range to 100000%..

**Comment by henhuy** [comment]
Indeed, the ranges are too wide now.
As for your example above - this is a tricky one, as choropleth legend and colors try to fit for all given values.
Now, range is very high, but even in older implementation the legend would go up to 27000%
We must add special behaviour for percentage choropleths in order to prevent this high values.
I will come up with a solution for both.

**Comment by nesnoj** [comment]
@henhuy Could you please have a look how this could be solved taking the issues from above into account?

**Comment by henhuy** [comment]
Fixed RE share legend to 100% - but then many municiaplities colored dark blue as they exceed 100%.
Good, or do you want to have it somehow different?

**Comment by henhuy** [comment]
> Fixed RE share legend to 100% - but then many municiaplities colored dark blue as they exceed 100%. Good, or do you want to have it somehow different?

Could you have a look @nesnoj ?

**Comment by nesnoj** [comment]
To list the issues and their status again:
- [x] 0-0 in Legend
- [x] choropleth for RE share
- [ ] _"Fixed RE share legend to 100% - but then many municipalities colored dark blue as they exceed 100%"_
Yes, this is a problem. It is better that having 27000 % like before but we need at least a >100% color value.
- [ ] Another problem that came up with your fixes: The colors for the bigger numbers are not used in many choropleths because of the larger ranges.
Example "Gewonnene Energie aus EE (GWh)" which goes up to 1000 instead of 400 so 600-800 and 800-1000 are not used at all:

Old:
image

New:
image

Can you solve this please?

**Comment by nesnoj** [comment]
Could you have a look @henhuy ?

**Comment by henhuy** [comment]
Hey @nesnoj please review again.
I made a rebase - so you have to throw away your current local branch and checkout fresh.
And you have to update poetry, as i had to update mapengine.

Please check different choropleths and especially chorpleths for energy shares (%)

**Comment by nesnoj** [comment]
From today @henhuy 
- Colors seem to be continuous and do not match discrete colors
- Increase default number of legend colors from 5 to 6
- The param `num_colors` in `static/config/choropleths.json` seem to have no effect :thinking:

**Comment by henhuy** [comment]
> From today @henhuy
> 
>     * Colors seem to be continuous and do not match discrete colors

Cannot change continuous coloring - there is no option to do so...
Only workaround would be to adapt feature data to match legend colors - would only do this if really necessary.

>     * Increase default number of legend colors from 5 to 6

Done.

>     * The param `num_colors` in `static/config/choropleths.json` seem to have no effect 🤔

There is a mismatched between chorpleth names i choropleth.json and choropleth.py. Once keys are mapping, number of legend entries gets adapted. For now, this is not needed, as I simply changed default number to 6 in mapengine.

**Comment by henhuy** [comment]
Would like to merge now and encounter continuous coloring in a new issue if necessary.

**Comment by nesnoj** [comment]
Thx @henhuy for the fix, looks good now! And do not worry about the continuous coloring.
However, the result popups do not work and raise
```
  File "/app/digiplan/map/charts.py", line 53, in render
    values = self.chart_data.iloc[i]
AttributeError: 'list' object has no attribute 'iloc'
```
pointing to your "Minor fix" in 4f0d0026a73c63a742f33b4889eddbac8999c296 . After undoing popups work again. What's the reason for this change?

**Comment by henhuy** [comment]
> What's the reason for this change?

A shit, this is due to pandas warnings in the console - but apparently `chart_data` isn't always a `pandas.Series` but can be a simple list as well. I will apply a quick fix.

**Comment by henhuy** [comment]
> I will apply a quick fix.

Done.

**Comment by nesnoj** [comment]
> > I will apply a quick fix.
> 
> Done.

Great, thanks! I'm happy to finally merge this :)

**Pull request merged**
