### PR TITLE
keep detail panel open on slider value change

### LINKED ISSUE #9: Detail settings panel closes on main slider change
See https://github.com/rl-institut/digiplan/issues/293

### PR DESCRIPTION
**Pull request by bmlancien**
I tried fixing the details panel closing on slider value change. Can you check if this is working now? 

close #9

### CODE REVIEW

**Comment by henhuy** [comment]
I'll check...

**Comment by henhuy** [comment]
Now it always opens the detail panel, even if panel hasn't been open before.
Is this intended? Wanted? you can decide @nesnoj 
Implementation looks good

**Comment by nesnoj** [comment]
> Now it always opens the detail panel, even if panel hasn't been open before. Is this intended? Wanted? you can decide @nesnoj Implementation looks good

Hmm that's odd, at my end everything works as expected (as @bmlancien I'm using docker).. any clue?

**Comment by nesnoj** [comment]
Is this still not working at your end @henhuy ?

**Comment by henhuy** [comment]
On my side it looks like this:
empowerplan_detail_slider

If this is intended - then everything is okay and we can merge!

**Comment by nesnoj** [comment]
Now I finally got what you mean..

The fact that the detail settings are switching as well when using a different main slider is ok for me. But this also happens when detail settings haven't been opened before.

Best solution was to only show the detail settings when they have been opened before (no matter for what technology), so kind of remembering the actual state. Is that easily possible @bmlancien ?

**Comment by bmlancien** [comment]
@nesnoj I think I would need some help for that one! I'm not sure where to look for...

**Comment by nesnoj** [comment]
> @nesnoj I think I would need some help for that one! I'm not sure where to look for...

@henhuy Could you assist?
But as the implemented solution is ok-ish, this is lower prio

**Comment by henhuy** [comment]
Should be working now!

**Review by nesnoj — APPROVED** [review]
LGTM, thx! :)

**Pull request merged**
