### PR TITLE
Show pre-results (without need for simulation run) on results page

### LINKED ISSUE #60: Indicate running optimization in result elements
As the optimization will take some time, split result into 2 steps:
5. "Ergebnisse" (instant results) - results which can be calculated without esys optimization (area usage, production, consumption). Optimization for 2. should start when this step is viewed.
6. "Detailergebnisse" (optimized esys results) - needs 1-4 min to be calculated

So we'd have 6 steps, which is quite a lot. Alternatively, instead of adding an additional one, the detailed results could be made available somewhere in the 5th step?

### PR DESCRIPTION
**Pull request by henhuy**
Closes #60 

TODOS:
- [x] Activate pre-results in results dropdown
- [x] Store simulation parameters server-side (pre-results ID)
- [x] deliver pre-results ID when requesting backend
- [x] Rewrite calculations to use only data from datapackage and pre-results parameters instead of simulation results (see TODOS below)

Calculations which have to be refactored:
- [x] electricity_demand_per_municipality_2045
- [x] heat_demand_per_municipality_2045

### CODE REVIEW

**Comment by henhuy** [comment]
Hey @nesnoj,

I just wanted to refactor electricity and heat demand calculation for 2045 (as currently this is calculated from simulation results instead of datapackage), but I stumble upon following lines.
https://github.com/empowerplan/epp-app/blob/8400d032eabe2b4561918ad47f20a862740b621d/digiplan/map/calculations.py#L358-L361
Do you know why we multiply values from 2045 with shares from 2022??
IMO, the shares are set up by user via GUI and should already be considered in demand sequences via hooks.
Cannot explain those lines - maybe you can enlighten me? THX

**Comment by nesnoj** [comment]
Yes, because 2022 is the reference which will be scaled according to the slider settings (relative changes), cf. my commit message for this line. Also, I changed the hooks accordingly in the same [commit](https://github.com/empowerplan/epp-app/commit/b09a43e48040e34391a73be0835d5abc2712d47c) those days. If I recall this correctly, there was an error in the calculation before..
But maybe I didn't fully understand the consideration in the hooks then - could you adjust this (back) and check if the passed energy amount to the esys equals the actual demand scaled by the slider settings?

PS: BTW, this is done for heat the very same way.. (line 359)

**Comment by henhuy** [comment]
- Implemented pre results for heat and electricity (including capita results)
- Activated chart results per default

Note:
- Choropleths show many black areas - this is due to missing data for most municipalities (as data is from digiplan, but municipalities are already present for empowerplan)
- Same goes for population dependent results, as population is from digiplan and does not fit
- Chart results must be marked as not ready yet if simulation is still runnning -> New PR for @bmlancien?
- Results dropdown elements depending on simulation are disabled -> no spinner next to option shown...

**Comment by henhuy** [comment]
Please review @nesnoj 
As said above, we could move pre-result design to extra issue if necessary

**Review by nesnoj — COMMENTED** [review]
Thx @henhuy!

While haven't checked every line, it looks plausible to me. Some notes and questions:
- The deactivation of dropdown elements is great
- I do not see any changes in the result charts yet
- When I select an available entry from dropdown while simulation is running (e.g. heat demand) the choropleth dowsn't show up and logs say `TypeError: can't multiply sequence by non-int of type 'float'`
- I extended the list `PRE_RESULTS` for the menu in menu.js to cover more results (actually all of the current entries can be precalculated)
- On the NaN/black areas: Data is available (some are dummy though) on the WAM-Server 
- (Why did you implement the pre-results as model? Design-driven decision?)

**Comment by henhuy** [comment]
> I do not see any changes in the result charts yet

Will move this to extra issue

> When I select an available entry from dropdown while simulation is running (e.g. heat demand) the choropleth dowsn't show up and logs say TypeError: can't multiply sequence by non-int of type 'float'

This works on my side. Do you have different data? (I'm using data from server)

> I extended the list PRE_RESULTS for the menu in menu.js to cover more results (actually all of the current entries can be precalculated)

I have to refactor calculations in order to not use simulation results. Maybe we have to discuss this for some calculations, as I'm not sure ALL selections can be pre-calculated...

> On the NaN/black areas: Data is available (some are dummy though) on the WAM-Server

No more black areas on my side. Downloaded data from server.

> (Why did you implement the pre-results as model? Design-driven decision?)

Internally, the map stores the pre-result ID and requests choropleths/popups/charts from backend using this ID. Alternative would be to store all form inputs of the user and query them within request. Maybe I switch to this, as waiting for pre-result ID takes too long IMO

**Comment by henhuy** [comment]
Should be ready now.
All results in dropdown are now available before finish of simulation run.
Also removed pre-results model.

> When I select an available entry from dropdown while simulation is running (e.g. heat demand) the choropleth dowsn't show up and logs say TypeError: can't multiply sequence by non-int of type 'float'

Is this still happening on your side?

Please review again. THX

**Comment by nesnoj** [comment]
> Should be ready now. All results in dropdown are now available before finish of simulation run. Also removed pre-results model.
> 
> > When I select an available entry from dropdown while simulation is running (e.g. heat demand) the choropleth dowsn't show up and logs say TypeError: can't multiply sequence by non-int of type 'float'
> 
> Is this still happening on your side?
> 
> Please review again. THX

No, but
```
  File "/app/digiplan/map/views.py", line 196, in get_charts
    {lookup: charts.CHARTS[lookup](user_settings=map_state).render() for lookup in lookups},
  File "/app/digiplan/map/views.py", line 196, in <dictcomp>
    {lookup: charts.CHARTS[lookup](user_settings=map_state).render() for lookup in lookups},
  File "/app/digiplan/map/charts.py", line 117, in __init__
    super().__init__()
  File "/app/digiplan/map/charts.py", line 28, in __init__
    self.chart_data = chart_data if chart_data is not None else self.get_chart_data()
  File "/app/digiplan/map/charts.py", line 492, in get_chart_data
    future_data = calculations.energies_per_municipality_2045(self.user_settings).sum().astype(float) * 1e-3
  File "/venv/lib/python3.9/site-packages/pandas/core/generic.py", line 6643, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "/venv/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 430, in astype
    return self.apply(
  File "/venv/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 363, in apply
    applied = getattr(b, f)(**kwargs)
  File "/venv/lib/python3.9/site-packages/pandas/core/internals/blocks.py", line 758, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "/venv/lib/python3.9/site-packages/pandas/core/dtypes/astype.py", line 237, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "/venv/lib/python3.9/site-packages/pandas/core/dtypes/astype.py", line 182, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
  File "/venv/lib/python3.9/site-packages/pandas/core/dtypes/astype.py", line 133, in _astype_nansafe
    return arr.astype(dtype, copy=True)
ValueError: could not convert string to float: ''
```

**Comment by henhuy** [comment]
> No, but

Ah yes! I did one change to your data.
Could you change `"bioenergy": "none"` to `"bioenergy": null` and try again?
As otherwise string `"none"` is causing this error.

**Review by nesnoj — APPROVED** [review]
Works out!

**Pull request merged**
