### PR TITLE
Feature/wind settings details

### LINKED ISSUE #25: Rework wind detail settings - timeslider
- Slider with 3 steps (timeline, sth. like increasing chart-like background):
  - **2018**: only descriptive
  - **2024**: only descriptive
  - **2027+** : descriptive and slider (usage)
- descriptive
  - 3-5 (?) key facts per step
  - 1 (i)-icon (at bottom?) to show more info (hover text)

### PR DESCRIPTION
**Pull request by bmlancien**
@nesnoj As agreed yesterday, I implemented the new design of the wind settings details sidepanel so that @henhuy can add the new data. Please review!

close #25

### CODE REVIEW

**Review by nesnoj — CHANGES_REQUESTED** [review]
Thx @bmlancien, looks good and works as expected :+1: .
However, we also talked sliders, could you please add
- one for 2024 (0..2 % in 0,2 % steps) and
- one for 2027+ (0..4 % in 0,2 % steps)

Like so:
image

**Comment by bmlancien** [comment]
I added placeholders for the sliders. For some reason they don't seem to be working as smoothly as on the left panel, but maybe that's because I don't really get the implementation behind the sliders and I didn't include them properly. Maybe as @henhuy works on them, they'll work better.

**Comment by nesnoj** [comment]
Thx! Ok, maybe @henhuy can help here..
One thing @bmlancien: All sliders now have the "attraction" color blue now, I guess this is not intended:
image

**Comment by bmlancien** [comment]
@nesnoj It was actually done on purpose. But thinking about it again, I changed it to a different shade of blue, so that it stays in touch with the EPP blue but is not too vibrant and therefore shouldn't compete with other controls. 

I also updated the "back" button because it shouldn't be as visible as the "next" button (the main goal is to move forward).

Same with the selected step on the wizard. It is not a control element, just an information, so it shouldn't have the EPP blue.

**Comment by nesnoj** [comment]
> @nesnoj It was actually done on purpose. But thinking about it again, I changed it to a different shade of blue, so that it stays in touch with the EPP blue but is not too vibrant and therefore shouldn't compete with other controls.
> 
> I also updated the "back" button because it shouldn't be as visible as the "next" button (the main goal is to move forward).
> 
> Same with the selected step on the wizard. It is not a control element, just an information, so it shouldn't have the EPP blue.

Ok thx. Color changes are fine for me, last todo here are the sliders @henhuy

**Comment by henhuy** [comment]
Oki. I take over. Just working on refactoring JS for sliders. Once this is done, I will work on this.

**Comment by henhuy** [comment]
> last todo here is the slider @henhuy

refactoring sliders.js solved the problem (as there were legacy calls connected to slider changes)

Should be ready to review now!

**Review by nesnoj — APPROVED** [review]
LGTM!

**Pull request merged**
