### PR TITLE
Integrate oemof tsam datapackage

### PR DESCRIPTION
**Pull request by henhuy**
Integrated TSAM datapackage. Simulation test run in 38s. Results looked good on first sight. 

Unfortunately, there is a bug with poetry installing oemof.tabular branch for TSAM.
Therefore, I had to add installation of oemof.tabular by using pip (instead of poetry).
This is added to Dockerfiles.
When not using docker, tabular must be installed by hand.

Please also update oemof datapackage using TSAm from https://wolke.rl-institut.de/s/FZfaRM9LE4tZ5Ng

### CODE REVIEW

**Review by nesnoj — APPROVED** [review]
Thx, I tried different scenario variations and it takes only 25 s at my end, yippiie! :)

One question: As you do not activate "tsam mode" explicitly, it is active by default? And how could one deactivate it? Also, can the tsam settings be controlled from the app?

I get 2 future warnings in the logs:
- **Django**: "/venv/lib/python3.9/site-packages/django_oemof/results.py:74: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  result = pandas.read_json(calculation_result.data, orient="table")"
- **Celery**: "[2024-05-01 12:19:39,774: WARNING/ForkPoolWorker-15] /venv/lib/python3.9/site-packages/oemof/solph/_models.py:558: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  self.flows[o, i].fix[t]"

**Comment by henhuy** [comment]
Nice! TSAM is hardwired into oemof datapackage (in fact one extra folder containing TSAM parameters). We could put original datapackage next to it and put a switch somewhere to change which datapackage should be used. But what could be the use case for a normal user?

**Comment by henhuy** [comment]
> * **Django**: "/venv/lib/python3.9/site-packages/django_oemof/results.py:74: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
>       result = pandas.read_json(calculation_result.data, orient="table")"

Will have a look thanks!

> * **Celery**: "[2024-05-01 12:19:39,774: WARNING/ForkPoolWorker-15] /venv/lib/python3.9/site-packages/oemof/solph/_models.py:558: FutureWarning: Series.**getitem** treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
>       self.flows[o, i].fix[t]"

This must be corrected in solph...

**Comment by henhuy** [comment]
> Will have a look thanks!

Moved to https://github.com/rl-institut/django-oemof/issues/4

**Comment by henhuy** [comment]
Shall we merge?

**Comment by nesnoj** [comment]
> Shall we merge?

Yess!! :+1:

**Pull request merged**
