### PR TITLE
Feature/scenario settings

### PR DESCRIPTION
**Pull request by josihoppe**

### CODE REVIEW

**Comment by josihoppe** [comment]
Sliders are adjusted for scenario settings. First the detail sliders are updated and then DETAIL_PANEL_SLIDER_CHANGE is changed to adapt main sliders. And after that the main/panel Sliders are updated with the scenario settings, but somehow the max value of the sliders (in the inside logic) is not changed, so the scenario setting can not move the slider beyond the "old" max value. And I don't know why.

**Review by henhuy — APPROVED** [review]
I really like your implementation!
I did two modifications:
- only read scenario.json once at beginning of module
- moved adapting of scenario sliders into scenario.js

Thanks for this!

**Comment by henhuy** [comment]
BTW, I did not change anything but moved adapting to scenarios.js - but somehow main slider adaption works now.
(I think there has been a change in flow, so that detail slider adaption and related main slider adaption happen before setting main slider value now)

**Comment by henhuy** [comment]
@nesnoj could you check if this works as expected on your machine too? Thx

**Review by nesnoj — COMMENTED** [review]
Thx, will check!
One thing I just noticed: The detail settings sidepanels do not close when clicking [X], console saying "closeSidepanel is not defined at HTMLButtonElement.onclick".
I guess after changing the script type of the `sliders.js` to "module" the ex- and import of this fct should be added?

**Review by nesnoj — CHANGES_REQUESTED** [review]
Works out as expected, thank you @josihoppe and @henhuy !
I'd have liked to have it implemented more generically (scenario site template which is filled with data from json or whatever) but to wrap up this quickly, this solution is good as it implements the most important features!

2 things:
- Please fix the detail panel bug described above (BTW, the closing via more arrow btns work, as this is implemented using `eventTopics.MORE_LABEL_CLICK`)
- I'd like to change the path to `scenarios.json` to the digipipe datapackage later, can I just change the path? The path to `scenarios.json` is hard coded in JS - if the file were taken from datapackage, should it be added to the [`config.py` instead like the other panel settings files](https://github.com/empowerplan/epp-app/blob/5db026547836e01f1852e57ced7f43908fac87f4/digiplan/map/config.py#L20-L27)?

**Comment by henhuy** [comment]
> * I'd like to change the path to `scenarios.json` to the digipipe datapackage later, can I just change the path? The path to `scenarios.json` is hard coded in JS - if the file were taken from datapackage, should it be added to the [`config.py` instead like the other panel settings files](https://github.com/empowerplan/epp-app/blob/5db026547836e01f1852e57ced7f43908fac87f4/digiplan/map/config.py#L20-L27)?

I also recommend to read path from config file.

**Comment by henhuy** [comment]
> * Please fix the detail panel bug described above (BTW, the closing via more arrow btns work, as this is implemented using `eventTopics.MORE_LABEL_CLICK`)

will fix

**Comment by nesnoj** [comment]
> > * I'd like to change the path to `scenarios.json` to the digipipe datapackage later, can I just change the path? The path to `scenarios.json` is hard coded in JS - if the file were taken from datapackage, should it be added to the [`config.py` instead like the other panel settings files](https://github.com/empowerplan/epp-app/blob/5db026547836e01f1852e57ced7f43908fac87f4/digiplan/map/config.py#L20-L27)?
> 
> I also recommend to read path from config file.

Could you please change this @josihoppe ?

**Comment by henhuy** [comment]
> Could you please change this @josihoppe ?

I will do

**Comment by henhuy** [comment]
Implemented change requests. Please review and merge

**Review by nesnoj — APPROVED** [review]
LGTM!

**Pull request merged**
